"""Pure regex parser for `devex.profile.ts`.

Extracts `testCommand` and `lintCommands` from the file generated by
`devex init`. Conservatively handles the format we produce; falls back to
returning empty results when the file is hand-edited in ways the regex
can't follow (template strings with interpolation, imports for the field
values, complex destructuring, etc.).

When the parser cannot extract values, the CLI should fall back to
explicit `--test` / `--lint` flags and report a helpful warning.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

# testCommand: 'value'  OR  testCommand: "value"  OR  testCommand: `value`
_TEST_RE = re.compile(r"testCommand\s*:\s*['\"`]([^'\"`]+)['\"`]")

# lintCommands: [ ... ] — multi-line possible, so use DOTALL.
_LINT_BLOCK_RE = re.compile(r"lintCommands\s*:\s*\[(.*?)\]", re.DOTALL)

# Match each quoted string inside the lintCommands block.
_STRING_RE = re.compile(r"['\"`]([^'\"`]+)['\"`]")

# Match /* ... */ block comments (possibly multi-line).
_BLOCK_COMMENT_RE = re.compile(r"/\*[\s\S]*?\*/")


def _strip_comments(content: str) -> str:
    """Remove TypeScript comments so the regex doesn't match commented-out fields.

    Handles:
      - `/* ... */` block comments (single- or multi-line)
      - Lines whose first non-whitespace characters are `//`

    Intentionally does NOT strip `//` mid-line — that preserves URLs like
    `'curl https://example.com'` inside `testCommand` values. A `//` mid-line
    meant as a comment is a documented edge case (the value before it still
    parses correctly; the comment tail is irrelevant to our extraction).
    """
    content = _BLOCK_COMMENT_RE.sub("", content)
    return "\n".join(
        line
        for line in content.splitlines()
        if not line.lstrip().startswith("//")
    )


@dataclass(frozen=True)
class ProfileCommands:
    """Commands extracted from a parsed `devex.profile.ts` file."""

    test_command: str | None
    lint_commands: tuple[str, ...]


def parse_profile_commands(profile_path: Path) -> ProfileCommands:
    """Parse `testCommand` and `lintCommands` from a profile file.

    Returns `ProfileCommands(test_command=None, lint_commands=())` when the
    file does not exist or the regex can't extract anything useful. Callers
    are expected to handle the empty case (warn + fall back to flags).
    """
    if not profile_path.exists():
        return ProfileCommands(test_command=None, lint_commands=())

    try:
        content = profile_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ProfileCommands(test_command=None, lint_commands=())

    content = _strip_comments(content)

    test_match = _TEST_RE.search(content)
    test_command = test_match.group(1) if test_match else None

    lint_block = _LINT_BLOCK_RE.search(content)
    lint_commands: tuple[str, ...] = ()
    if lint_block:
        lint_commands = tuple(m.group(1) for m in _STRING_RE.finditer(lint_block.group(1)))

    return ProfileCommands(test_command=test_command, lint_commands=lint_commands)


def resolve_check_commands(
    profile_path: Path,
    *,
    explicit_test: str | None,
    explicit_lint: list[str],
) -> ProfileCommands:
    """Layered resolution: explicit flags > parsed profile > empty.

    - If the caller passed `--test` or `--lint`, those win — return them
      directly (the parsed profile is ignored to avoid mixing sources).
    - Otherwise, parse the profile.
    """
    if explicit_test is not None or explicit_lint:
        return ProfileCommands(
            test_command=explicit_test,
            lint_commands=tuple(explicit_lint),
        )
    return parse_profile_commands(profile_path)
